config/routes.rb
Rails.application.routes.draw do
  root 'bicycles#index'
  resources :bicycles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]

  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.all
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/_form.html.erb
<%= form_with(model: bicycle, local: true) do |form| %>
  <% if bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicycles/edit.html.erb
<h1>Editing Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Show', @bicycle %> |
<%= link_to 'Back', bicycles_path %>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicycles</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.year %></td>
        <td><%= link_to 'Show', bicycle %></td>
        <td><%= link_to 'Edit', edit_bicycle_path(bicycle) %></td>
        <td><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bicycle', new_bicycle_path %>

app/views/bicycles/new.html.erb
<h1>New Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Back', bicycles_path %>

app/views/bicycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @bicycle.year %>
</p>

<%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
<%= link_to 'Back', bicycles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaffasdelsol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>